openapi: 3.0.0
info:
  title: service
  version: '1.0'
servers:
  - url: 'https://finvault-api.herokuapp.com/'
paths:
  /service:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
      operationId: get-service
components:
  schemas: {}
